# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1299, 871)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Users/user/Desktop/아이콘.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../../../Users/user/Desktop/아이콘.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color:rgb(226,226,228);\n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.label.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 111, 16))
        self.label_2.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";")
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(210, 130, 391, 321))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"\n"
"             \n"
"                border: 2px solid rgb(160,160,160);\n"
"                border-radius: 5px;\n"
"            }")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(27)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 20, 581, 71))
        self.frame_2.setStyleSheet("QFrame{\n"
"\n"
"               \n"
"                border: 2px solid rgb(160,160,160);\n"
"                border-radius: 5px;\n"
"            }")
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.algorithm = QtWidgets.QComboBox(self.frame_2)
        self.algorithm.setGeometry(QtCore.QRect(90, 10, 111, 22))
        self.algorithm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.algorithm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.algorithm.setStyleSheet("font: 63 9pt \"Bahnschrift SemiBold\";")
        self.algorithm.setIconSize(QtCore.QSize(10, 10))
        self.algorithm.setObjectName("algorithm")
        self.algorithm.addItem("")
        self.algorithm.addItem("")
        self.algorithm.addItem("")
        self.algorithm.addItem("")
        self.algorithm.addItem("")
        self.algorithm.addItem("")
        self.Time_Quantum = QtWidgets.QLineEdit(self.frame_2)
        self.Time_Quantum.setGeometry(QtCore.QRect(110, 40, 91, 20))
        self.Time_Quantum.setStyleSheet("QLineEdit {\n"
"                \n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }")
        self.Time_Quantum.setObjectName("Time_Quantum")
        self.run_button = QtWidgets.QPushButton(self.frame_2)
        self.run_button.setGeometry(QtCore.QRect(280, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.run_button.setFont(font)
        self.run_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_button.setStyleSheet("QPushButton {\n"
"                color: white;\n"
"                background-color: rgb(71, 144, 209);\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: white;\n"
"                color: rgb(71,144,209);\n"
"            }\n"
"QPushButton:pressed{\n"
"    background-color:rgb(71,144,209);\n"
"    color :white;\n"
"}")
        self.run_button.setObjectName("run_button")
        self.random_button = QtWidgets.QPushButton(self.centralwidget)
        self.random_button.setGeometry(QtCore.QRect(30, 400, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.random_button.setFont(font)
        self.random_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.random_button.setStyleSheet("QPushButton {\n"
"                color: rgb(71, 144, 209);\n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(71, 144, 209);\n"
"                color: white;\n"
"            }\n"
"QPushButton:pressed{\n"
"    background-color:white;\n"
"    color :rgb(71, 144, 209);\n"
"}")
        self.random_button.setObjectName("random_button")
        self.Process_ID = QtWidgets.QLineEdit(self.centralwidget)
        self.Process_ID.setGeometry(QtCore.QRect(30, 160, 151, 21))
        self.Process_ID.setStyleSheet("QLineEdit {\n"
"                \n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }")
        self.Process_ID.setFrame(True)
        self.Process_ID.setObjectName("Process_ID")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 111, 16))
        self.label_6.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";")
        self.label_6.setObjectName("label_6")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(30, 340, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_button.setFont(font)
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_button.setStyleSheet("QPushButton {\n"
"                color: rgb(71, 144, 209);\n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(71, 144, 209);\n"
"                color: white;\n"
"            }\n"
"QPushButton:pressed{\n"
"    background-color:white;\n"
"    color :rgb(71, 144, 209);\n"
"}")
        self.delete_button.setObjectName("delete_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(30, 290, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_button.setFont(font)
        self.add_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_button.setStyleSheet("QPushButton {\n"
"                color: rgb(71, 144, 209);\n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }\n"
" QPushButton:hover {\n"
"                background-color: rgb(71, 144, 209);\n"
"                color: white;\n"
"            }\n"
"QPushButton:pressed{\n"
"    background-color:white;\n"
"    color :rgb(71, 144, 209);\n"
"}")
        self.add_button.setObjectName("add_button")
        self.Process_AT = QtWidgets.QLineEdit(self.centralwidget)
        self.Process_AT.setGeometry(QtCore.QRect(30, 210, 151, 21))
        self.Process_AT.setStyleSheet("QLineEdit {\n"
"                \n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }")
        self.Process_AT.setObjectName("Process_AT")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 240, 111, 16))
        self.label_7.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 140, 121, 16))
        self.label_8.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";")
        self.label_8.setObjectName("label_8")
        self.Process_BT = QtWidgets.QLineEdit(self.centralwidget)
        self.Process_BT.setGeometry(QtCore.QRect(30, 260, 151, 21))
        self.Process_BT.setStyleSheet("QLineEdit {\n"
"                \n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }")
        self.Process_BT.setObjectName("Process_BT")
        self.AllDelete_button = QtWidgets.QPushButton(self.centralwidget)
        self.AllDelete_button.setGeometry(QtCore.QRect(110, 400, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AllDelete_button.setFont(font)
        self.AllDelete_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AllDelete_button.setStyleSheet("QPushButton {\n"
"                color: rgb(71, 144, 209);\n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(71, 144, 209);\n"
"                color: white;\n"
"            }\n"
"QPushButton:pressed{\n"
"    background-color:white;\n"
"    color :rgb(71, 144, 209);\n"
"}")
        self.AllDelete_button.setObjectName("AllDelete_button")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 130, 181, 321))
        self.frame_3.setStyleSheet("QFrame{\n"
"\n"
"               \n"
"                border: 2px solid rgb(160,160,160);\n"
"                border-radius: 5px;\n"
"            }")
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.resultTable = QtWidgets.QTableWidget(self.centralwidget)
        self.resultTable.setGeometry(QtCore.QRect(20, 490, 581, 351))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.resultTable.setFont(font)
        self.resultTable.setStyleSheet("QTableWidget{\n"
"\n"
"             \n"
"                border: 2px solid rgb(160,160,160);\n"
"                border-radius: 5px;\n"
"            }")
        self.resultTable.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.resultTable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.resultTable.setLineWidth(1)
        self.resultTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.resultTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.resultTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.resultTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.resultTable.setWordWrap(True)
        self.resultTable.setCornerButtonEnabled(True)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(6)
        self.resultTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTable.setHorizontalHeaderItem(5, item)
        self.resultTable.verticalHeader().setMinimumSectionSize(27)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 460, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 0, 1301, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(610, 100, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";")
        self.label_5.setObjectName("label_5")
        self.add_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.add_button_2.setGeometry(QtCore.QRect(620, 200, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_button_2.setFont(font)
        self.add_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_button_2.setStyleSheet("QPushButton {\n"
"                color: rgb(71, 144, 209);\n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }\n"
" QPushButton:hover {\n"
"                background-color: rgb(71, 144, 209);\n"
"                color: white;\n"
"            }\n"
"QPushButton:pressed{\n"
"    background-color:white;\n"
"    color :rgb(71, 144, 209);\n"
"}")
        self.add_button_2.setObjectName("add_button_2")
        self.AllDelete_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.AllDelete_button_2.setGeometry(QtCore.QRect(700, 300, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AllDelete_button_2.setFont(font)
        self.AllDelete_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AllDelete_button_2.setStyleSheet("QPushButton {\n"
"                color: rgb(71, 144, 209);\n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(71, 144, 209);\n"
"                color: white;\n"
"            }\n"
"QPushButton:pressed{\n"
"    background-color:white;\n"
"    color :rgb(71, 144, 209);\n"
"}")
        self.AllDelete_button_2.setObjectName("AllDelete_button_2")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(610, 130, 181, 221))
        self.frame_4.setStyleSheet("QFrame{\n"
"\n"
"               \n"
"                border: 2px solid rgb(160,160,160);\n"
"                border-radius: 5px;\n"
"            }")
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.coreType = QtWidgets.QComboBox(self.frame_4)
        self.coreType.setGeometry(QtCore.QRect(10, 40, 151, 22))
        self.coreType.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.coreType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.coreType.setStyleSheet("font: 63 9pt \"Bahnschrift SemiBold\";")
        self.coreType.setIconSize(QtCore.QSize(10, 10))
        self.coreType.setObjectName("coreType")
        self.coreType.addItem("")
        self.coreType.addItem("")
        self.coreTable = QtWidgets.QTableWidget(self.centralwidget)
        self.coreTable.setGeometry(QtCore.QRect(800, 130, 391, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.coreTable.sizePolicy().hasHeightForWidth())
        self.coreTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.coreTable.setFont(font)
        self.coreTable.setStyleSheet("QTableWidget{\n"
"\n"
"             \n"
"                border: 2px solid rgb(160,160,160);\n"
"                border-radius: 5px;\n"
"            }")
        self.coreTable.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.coreTable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.coreTable.setLineWidth(1)
        self.coreTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.coreTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.coreTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.coreTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.coreTable.setWordWrap(True)
        self.coreTable.setCornerButtonEnabled(True)
        self.coreTable.setObjectName("coreTable")
        self.coreTable.setColumnCount(0)
        self.coreTable.setRowCount(0)
        self.coreTable.verticalHeader().setMinimumSectionSize(27)
        self.random_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.random_button_2.setGeometry(QtCore.QRect(620, 300, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.random_button_2.setFont(font)
        self.random_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.random_button_2.setStyleSheet("QPushButton {\n"
"                color: rgb(71, 144, 209);\n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(71, 144, 209);\n"
"                color: white;\n"
"            }\n"
"QPushButton:pressed{\n"
"    background-color:white;\n"
"    color :rgb(71, 144, 209);\n"
"}")
        self.random_button_2.setObjectName("random_button_2")
        self.delete_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button_2.setGeometry(QtCore.QRect(620, 250, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_button_2.setFont(font)
        self.delete_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_button_2.setStyleSheet("QPushButton {\n"
"                color: rgb(71, 144, 209);\n"
"                background-color: white;\n"
"                border: 2px solid rgb(71, 144, 209);\n"
"                border-radius: 5px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(71, 144, 209);\n"
"                color: white;\n"
"            }\n"
"QPushButton:pressed{\n"
"    background-color:white;\n"
"    color :rgb(71, 144, 209);\n"
"}")
        self.delete_button_2.setObjectName("delete_button_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(620, 140, 111, 16))
        self.label_10.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";")
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(810, 360, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";")
        self.label_9.setObjectName("label_9")
        self.totalconsumption = QtWidgets.QLabel(self.centralwidget)
        self.totalconsumption.setGeometry(QtCore.QRect(1040, 360, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.totalconsumption.setFont(font)
        self.totalconsumption.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";")
        self.totalconsumption.setObjectName("totalconsumption")
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.tableWidget.raise_()
        self.random_button.raise_()
        self.Process_ID.raise_()
        self.label_6.raise_()
        self.delete_button.raise_()
        self.add_button.raise_()
        self.Process_AT.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.Process_BT.raise_()
        self.AllDelete_button.raise_()
        self.resultTable.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.line.raise_()
        self.label_5.raise_()
        self.add_button_2.raise_()
        self.AllDelete_button_2.raise_()
        self.coreTable.raise_()
        self.random_button_2.raise_()
        self.delete_button_2.raise_()
        self.label_10.raise_()
        self.label_9.raise_()
        self.totalconsumption.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1299, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Process Scheduling"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Algorithm :</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Time Quantum :</span></p></body></html>"))
        self.tableWidget.setSortingEnabled(False)
        self.algorithm.setItemText(0, _translate("MainWindow", "FCFS"))
        self.algorithm.setItemText(1, _translate("MainWindow", "RR"))
        self.algorithm.setItemText(2, _translate("MainWindow", "SPN"))
        self.algorithm.setItemText(3, _translate("MainWindow", "SRTN"))
        self.algorithm.setItemText(4, _translate("MainWindow", "HRRN"))
        self.algorithm.setItemText(5, _translate("MainWindow", "OUR"))
        self.run_button.setText(_translate("MainWindow", "GO"))
        self.random_button.setText(_translate("MainWindow", "RANDOM"))
        self.label_6.setText(_translate("MainWindow", "Arrival Time"))
        self.delete_button.setText(_translate("MainWindow", "DELETE"))
        self.add_button.setText(_translate("MainWindow", "ADD"))
        self.label_7.setText(_translate("MainWindow", "Burst Time"))
        self.label_8.setText(_translate("MainWindow", "Process ID"))
        self.AllDelete_button.setText(_translate("MainWindow", "CLEAR"))
        self.resultTable.setSortingEnabled(False)
        item = self.resultTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Process ID"))
        item = self.resultTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "AT"))
        item = self.resultTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "BT"))
        item = self.resultTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "WT"))
        item = self.resultTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "BT"))
        item = self.resultTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "NTT"))
        self.label_3.setText(_translate("MainWindow", "Process List"))
        self.label_4.setText(_translate("MainWindow", "Scheduling Result"))
        self.label_5.setText(_translate("MainWindow", "Processor"))
        self.add_button_2.setText(_translate("MainWindow", "ADD"))
        self.AllDelete_button_2.setText(_translate("MainWindow", "CLEAR"))
        self.coreType.setItemText(0, _translate("MainWindow", "P-Core"))
        self.coreType.setItemText(1, _translate("MainWindow", "E-Core"))
        self.coreTable.setSortingEnabled(False)
        self.random_button_2.setText(_translate("MainWindow", "RANDOM"))
        self.delete_button_2.setText(_translate("MainWindow", "DELETE"))
        self.label_10.setText(_translate("MainWindow", "Core Type"))
        self.label_9.setText(_translate("MainWindow", "Total Power Consumption:"))
        self.totalconsumption.setText(_translate("MainWindow", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
