# -*- coding: utf-8 -*-
"""process.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yglA1r5B62kl-jzSd3lZhoab3kVVrlKk
"""

class process() :
  proc_name = 'p1'
  a_time = 0 #arrive time
  b_time = 0 #brust time
  lb_time = b_time #left brust time
  w_time = 0 #wait time
  ta_time = 0 #turnaround_time
  nt_time = 0 #normalized turnaround time
  res_ratio = 0 #Response ratio

  def value_input(self, name = 'p1' , arr_time = 0, bst_time = 0) :
    self.a_time = arr_time
    self.b_time = bst_time
    self.proc_name = name

  def advence_progress(self, processor_work_val) :
    if (self.lb_time - processor_work_val) < 0 :
      self.lb_time = 0
    else : 
      self.lb_time -= processor_work_val

  def job_done(self, undone_list, done_list) : 
    undone_list.remove(self)
    done_list.append(self)
    self.ta_time = self.b_time + self.w_time
    self.nt_time = self.ta_time / self.b_time

  def res_check(self) :
    self.res_ratio = (self.lb_time + self.w_time) / self.lb_time

def proc_add(*, num = 1, arr_time = 0, bst_time = 0) :
  name = f'P{num}'
  globals()[name] = process()
  exec('name.value_input(name, arr_time, bst_time)')


if __name__ == '__main__' :
  prosecce_list = []
  un_done_list = []
  done_list = []
  

  for i in range(3) :
    input_num = input('프로세스 번호를 입력하시오 : ')
    input_arr = int(input('프로세스 도착시간을 입력하시오 : '))
    input_bst = int(input('프로세스 실행시간을 입력하시오 : '))
    proc_add(name = input_nam, arr_time = input_arr, bst_time = input_bst)
    prosecce_list.append(globals()[input_nam])
    print(prosecce_list)